In [2]:
import pandas as pd
import numpy as np
import re

archivo = "plan_de_compras_2025.xlsx"

df = pd.read_excel(archivo)
df[["Código presupuestario", "Nombre Proyecto"]].head(10)

  Código presupuestario                                    Nombre Proyecto
0          2207-2209-33  Servicio arriendo de una plataforma de gestión...
1          2206-2206001  Servicio de Mantención y Reparaciones Menores ...
2               2204001           Servicios de Impresión-Seremi Valparaiso
3               2209006  Servicio de Arriendo de Impresoras Multifuncio...
4               2205005       Servicio de Telefonía Fija-Seremi Valparaiso
5                  2207  SERVICIO DE EMPASTES Y ENCUADERNACION- Sección...
6                  2209  Arriendo de impresoras multifuncionales- Secci...
7                  2205  Servicio de Telefonia Satelital- Sección Contr...
8                  2205  Servicio de Telefonia Satelital- Sección Contr...
9                  2208  Servicio del limpieza interna y externa y exte...

In [ ]:
# transformacion de nombre de proyecto basado en codigos unicos
codigos = pd.read_excel('codigos_unicos.xlsx')
# Asegurar que las columnas de cruce tengan formato string sin espacios extra
df['Código presupuestario'] = df['Código presupuestario'].astype(str).str.strip()
codigos['Codigo'] = codigos['Codigo'].astype(str).str.strip()

# Realizar el Join entre df y codigos
df_merged = df.merge(
    codigos[['Codigo', 'Nombre']], 
    left_on='Código presupuestario',
    right_on='Codigo', 
    how='left'
)

# Reemplazar los valores en 'Nombre Proyecto' con el nuevo 'Nombre' obtenido del join
# Se mantiene el valor original en caso de que no haya coincidencia
df['Nombre Proyecto'] = df_merged['Nombre'].fillna(df['Nombre Proyecto'])

df[["Código presupuestario", "Nombre Proyecto"]].head(10)

  Código presupuestario                                    Nombre Proyecto
0          2207-2209-33  Servicio arriendo de una plataforma de gestión...
1          2206-2206001  Servicio de Mantención y Reparaciones Menores ...
2               2204001                             MATERIAL DE ESCRITORIO
3               2209006  Arriendo PC Ampliación (465) - División Inform...
4               2205005                         Servicio de Telefonía Fija
5                  2207              SERVICIO DE EMPASTES Y ENCUADERNACION
6                  2209            Arriendo de impresoras multifuncionales
7                  2205                    Servicio de Telefonia Satelital
8                  2205                    Servicio de Telefonia Satelital
9                  2208            Servicio del limpieza interna y externa